export default [
    {
        "id":"criterion1",
        "description":"first",
        "variants":[
            "first",
            "second",
            "third"
        ]
    },
    {
        "id":"criterion2",
        "description":"Second",
        "variants":[
            "first",
            "second",
            "third"
        ]
    },
    {
        "id":"criterion3",
        "description":"3",
        "variants":[
            "first",
            "second",
            "third"
        ]
    },
    {
        "id":"criterion4",
        "description":"4",
        "variants":[
            "first",
            "second",
            "third"
        ]
    }
]

