export default {
    GET_SEARCH_FIELD_VALUE: 'GET_SEARCH_FIELD_VALUE',
    IS_LOGIN:'IS_LOGIN',
    GET_USER_DATA:'GET_USER_DATA',
    LOGOUT:'LOGOUT',
    IS_ADMIN:'IS_ADMIN',
    GET_CONCERTS:'GET_CONCERTS',
    GET_BOOKINGS:'GET_BOOKINGS'
}